import { useState, useMemo } from 'react';
import Lightbox from "yet-another-react-lightbox";
import Fullscreen from "yet-another-react-lightbox/plugins/fullscreen";
import Zoom from "yet-another-react-lightbox/plugins/zoom";
import "yet-another-react-lightbox/styles.css";

// Import the manifest file generated by our Node.js script.
import manifest from '../galleryManifest.json';

export default function ImageGallery({ path }) {
  const [isOpen, setIsOpen] = useState(false);
  const [currentIndex, setCurrentIndex] = useState(0);

  // Function to detect if filename should show a nickname
  const extractNickname = (filename) => {
    // Remove file extension
    const nameWithoutExt = filename.substring(0, filename.lastIndexOf('.'));
    
    // Remove thumbnail suffixes if present (including (Custom))
    const cleanName = nameWithoutExt
      .replace(/_thumb$|_thumbnail$|-thumb$/i, '')
      .replace(/\s*\(Custom\)$/i, '');
    
    // Check if it's a date format (YYYY-MM-DD_HH.MM.SS or similar)
    const datePattern = /^\d{4}-\d{2}-\d{2}_\d{2}\.\d{2}\.\d{2}$/;
    if (datePattern.test(cleanName)) {
      return null;
    }
    
    // Check if it's a generic image name (image1, image2, etc.)
    const genericPattern = /^image\d+$/i;
    if (genericPattern.test(cleanName)) {
      return null;
    }
    
    // Check if it has underscore (player nickname pattern)
    const firstUnderscoreIndex = cleanName.indexOf('_');
    if (firstUnderscoreIndex !== -1) {
      const potentialNickname = cleanName.substring(0, firstUnderscoreIndex);
      
      // Additional checks
      if (potentialNickname.includes('.') || potentialNickname.includes('-')) {
        return null;
      }
      
      if (/^\d+$/.test(potentialNickname)) {
        return null;
      }
      
      // Check if it's a valid Minecraft-like nickname (alphanumeric with possible underscores)
      if (/^[a-zA-Z][a-zA-Z0-9_]*$/.test(potentialNickname)) {
        return potentialNickname;
      }
      
      return null;
    }
    
    // No underscore - check if the whole name looks like a nickname
    if (cleanName.length > 2 && cleanName.length <= 16 && /^[a-zA-Z][a-zA-Z0-9_]*$/.test(cleanName)) {
      return cleanName;
    }
    
    return null;
  };

  const galleryImages = useMemo(() => {
    const imageData = manifest[path];

    if (!imageData || imageData.length === 0) {
      return [];
    }

    // Handle both old format (array of strings) and new format (array of objects)
    return imageData.map(item => {
      let filename, thumbnail;
      
      if (typeof item === 'string') {
        // Old format compatibility
        filename = item;
        thumbnail = null;
      } else {
        // New format with thumbnail support
        filename = item.filename;
        thumbnail = item.thumbnail;
      }
      
      const nickname = extractNickname(filename);
      const fullUrl = `/news/images/${path}/${filename}`;
      const thumbUrl = thumbnail ? `/news/images/${path}/${thumbnail}` : fullUrl;

      return {
        src: fullUrl,           // Full image for lightbox
        thumb: thumbUrl,        // Thumbnail for grid (falls back to full if no thumbnail)
        mc: nickname || '',
        name: nickname || '',
        hasNickname: !!nickname,
        hasThumbnail: !!thumbnail
      };
    });
  }, [path]);

  if (galleryImages.length === 0) {
    console.warn(`ImageGallery: No images found for path: "${path}" in manifest.`);
    return <p className="text-gray-400">Галерею не знайдено або в ній немає зображень.</p>;
  }
  
  const openLightbox = (index) => {
    setCurrentIndex(index);
    setIsOpen(true);
  };

  return (
    <div className="my-6">
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
        {galleryImages.map((img, index) => (
          <div
            key={index}
            className="group relative cursor-pointer overflow-hidden cornerCutSmall aspect-square"
            onClick={() => openLightbox(index)}
          >
            {/* Use thumbnail for grid view if available */}
            <img
              src={img.thumb}
              alt={img.hasNickname ? `Гравець ${img.name}` : 'Зображення галереї'}
              className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
              style={{ imageRendering: 'pixelated' }}
              loading="lazy"
            />
            
            {/* Small indicator if using thumbnail - improved style */}
            {img.hasThumbnail && (
              <div className="absolute top-2 right-2">
                {/* Outer div acts as border */}
                <div className="cornerCutSmall bg-white/30 p-[2px]">
                  {/* Inner div with content */}
                  <div className="cornerCutSmall bg-black/40 px-2 py-0.5 flex items-center justify-center w-10 h-10">
                    <span className="text-xs text-white font-bold">HD</span>
                  </div>
                </div>
              </div>
            )}

            {/* Nickname overlay */}
            {img.hasNickname && (
              <div
                className="absolute bottom-0 left-0 right-0 p-2 flex items-center gap-2 bg-gradient-to-t from-black/70 to-transparent minecraftFont"
              >
                <img
                  src={`https://nmsr.nickac.dev/face/${img.mc}`}
                  alt={img.name}
                  className="w-5 h-5 object-cover flex-shrink-0"
                  style={{ imageRendering: 'pixelated' }}
                  onError={(e) => { e.target.style.display = 'none'; }}
                />
                <span className="text-sm font-medium text-white drop-shadow-md truncate">
                  {img.name}
                </span>
              </div>
            )}
          </div>
        ))}
      </div>

      <Lightbox
        open={isOpen}
        close={() => setIsOpen(false)}
        slides={galleryImages.map(img => ({ src: img.src }))}
        index={currentIndex}
        plugins={[Fullscreen, Zoom]}
        zoom={{
          maxZoomPixelRatio: 10,
          zoomInMultiplier: 2,
          doubleTapDelay: 300,
          doubleClickDelay: 300,
          doubleClickMaxStops: 2,
          keyboardMoveDistance: 50,
          wheelZoomDistanceFactor: 100,
          pinchZoomDistanceFactor: 100,
          scrollToZoom: true,
        }}
        styles={{ 
          container: { 
            backgroundColor: "rgba(32, 44, 40, 0.98)",
            height: "100vh",
            width: "100vw"
          },
          slide: {
            display: "flex",
            alignItems: "center",
            justifyContent: "center"
          },
          slideContainer: {
            height: "100%",
            width: "100%"
          },
          image: {
            imageRendering: "pixelated",
            maxHeight: "100vh",
            maxWidth: "100vw",
            objectFit: "contain"
          }
        }}
        carousel={{
          finite: false,
          preload: 2,
          imageFit: "contain",
          imageProps: {
            style: {
              imageRendering: "pixelated",
            }
          }
        }}
      />

      {/* Global CSS override for Minecraft-themed lightbox */}
      <style jsx global>{`
        /* Pixelated images */
        .yarl__slide img,
        .yarl__slide_image,
        .yarl__slide_zoomed img {
          image-rendering: pixelated !important;
          image-rendering: -moz-crisp-edges !important;
          image-rendering: crisp-edges !important;
        }
        
        /* Main container background */
        .yarl__container {
          height: 100vh !important;
          width: 100vw !important;
          background: linear-gradient(135deg, rgba(32, 44, 40, 0.98) 0%, rgba(69, 33, 54, 0.95) 100%) !important;
        }

        /* Minecraft-style Buttons with 3D Bevel */
        .yarl__button {
          background: linear-gradient(180deg, #c5629a 0%, #a34e7e 100%) !important;
          border: none !important;
          border-radius: 0 !important;
          color: #e5e7eb !important;
          transition: all 0.1s ease !important;
          min-width: 44px !important;
          min-height: 44px !important;
          padding: 10px !important;
          image-rendering: pixelated !important;
        }

        /* Hover state: "pop out" effect */
        .yarl__button:hover {
          background: linear-gradient(180deg, #f390d0 0%, #c5629a 100%) !important;
        }

        /* Active state: "pushed in" effect */
        .yarl__button:active {
          background: linear-gradient(180deg, #a34e7e 0%, #823e65 100%) !important;
        }

        /* Navigation buttons (larger) */
        .yarl__navigation_prev,
        .yarl__navigation_next {
          margin: 0 10px !important;
          padding: 20px !important;
          background: linear-gradient(180deg, #c5629a 0%, #a34e7e 100%) !important;
        }

        .yarl__navigation_prev .yarl__button,
        .yarl__navigation_next .yarl__button {
          width: 56px !important;
          height: 56px !important;
        }

        /* Toolbar with Minecraft style */
        .yarl__toolbar {
          padding: 12px !important;
          gap: 8px !important;
        }

        /* Slide counter with Minecraft UI style */
        .yarl__slide_counter {
          background: #202c28 !important;
          color: #e5e7eb !important;
          font-family: 'Minecraft', monospace !important;
          font-weight: bold !important;
          padding: 8px 16px !important;
          border-radius: 0 !important;
        }

        /* Loading spinner color */
        .yarl__loading {
          color: #c5629a !important;
        }

        /* Icon styling */
        .yarl__icon {
          color: #e5e7eb !important;
          image-rendering: pixelated !important;
          filter: drop-shadow(2px 2px 0px rgba(0, 0, 0, 0.3)) !important;
        }
      `}</style>
    </div>
  );
}